Tela de cardápio e detalhamento de item
gusthawojunkes/feedy pull request #10
Opened 2022-04-10 23:42 UTC by Nathan-Stuber-Antunes

Cardápio
![image](https://user-images.githubusercontent.com/51455214/162645000-6e6379fc-dd1f-4e32-a82d-dd82d10bc32e.png)

Detalhamento do Item:
![image](https://user-images.githubusercontent.com/51455214/162645005-1c557b61-5736-4883-ae45-c5dbbe052651.png)

2022-04-12 22:17 UTC, gusthawoibt requested changes

2022-04-12 22:17 UTC, gusthawoibt commented on src/App.vue
> +        <AppBarVue />
Se você colocar o `v-app-bar` aqui no `App.vue` ele vai percorrer o que você colocou por toda a aplicação, nesse caso o a palavra "Cardápio" vai estar em todas as telas.

2022-04-12 22:17 UTC, gusthawoibt commented on src/components/BottomNavigation.vue
> +export default defineComponent({ data: () => ({ value: 'bottom-navigation' }) });
Sempre que você criar um componente de tela, adicione a propriedade `name` dentro do objeto que vai passar para o método `defineComponent({})`. Coloque o mesmo nome do arquivo como os demais. Sem essa propriedade pode ser que o Vue se perca e não ache o componente.

2022-04-12 22:17 UTC, gusthawoibt commented on src/components/Menu/ProductList.vue
> +                    <v-img :src="semImagem" height="150px" cover></v-img>
A chamada deveria ser algo como `item.image` mas como não temos dados ainda ok, fica como template por enquanto.

2022-04-12 22:17 UTC, gusthawoibt commented on src/components/Menu/ProductList.vue
> +import semImagem from '@/assets/semImagem.png';
Exemplo de um `import` mais "clean".

2022-04-12 22:17 UTC, gusthawoibt commented on src/components/Menu/ProductList.vue
> +            itens: [
Mesmo que ainda não tenhamos dados no banco, não chumbar os objetos aqui. Poderia ter já feito o método que puxa os produtos, aí depois nós já teríamos o método pronto e tudo rodaria sem ter alterações muito grandes.

2022-04-12 22:42 UTC, Nathan-Stuber-Antunes commented on src/App.vue
> +        <AppBarVue />
Sim, coloquei esse cara para a utilização deste desenvolvimento inicial. Tenho que por de forma dinâmica para obter conforme a página do usuário.

2022-04-12 22:43 UTC, Nathan-Stuber-Antunes commented on src/App.vue
> +import AppBarVue from './components/AppBar.vue';
Verdade, esqueci desse detalhe.

2022-04-12 22:49 UTC, Nathan-Stuber-Antunes commented on src/components/BottomNavigation.vue
> +export default defineComponent({ data: () => ({ value: 'bottom-navigation' }) });
Ok.

2022-04-20 23:36 UTC, gusthawojunkes approved these changes

2022-04-20 23:37 UTC, merged