Melhorias na tela de pedidos
gusthawojunkes/feedy pull request #10
Opened 2022-06-11 17:46 UTC by gusthawojunkes

2022-06-14 00:54 UTC, Nathan-Stuber-Antunes requested changes

2022-06-14 00:54 UTC, Nathan-Stuber-Antunes commented on src/services/order.service.js
> +        console.log(order);
Ta só com o console.log porque ainda vai ser desenvolvido?

2022-06-15 22:11 UTC, gusthawojunkes commented on src/services/order.service.js
> +        console.log(order);
Sim.

2022-06-15 22:15 UTC, Nathan-Stuber-Antunes approved these changes

2022-06-15 22:15 UTC, merged